
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhuipvvcnbyagkwetmgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodWlwdnZjbmJ5YWdrd2V0bWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzM2MjgsImV4cCI6MjA1ODQ0OTYyOH0.IZyemOsXajNf33v5kngL4gps8CxJKVPXBurFuU8ShKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
